### ISSUE TITLE
Write automated tests for the SQL queries

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/zap-api#76]
We need automated tests for the SQL queries in our API
- projects/show.sql
- projects/index.sql
- assignments/index.sql

**Comment by allthesignals** [comment]
Some communications problems have blocked the retrieval of a fresh production database that would reflect latest changes.

I'm going to write a few test cases to see what I can test for the time being.

**Comment by allthesignals** [comment]
- [ ] Run migrations against a local database
 - [ ] Write some tests which fill that database and assert against
 - [ ] See if we need factories (informed by real database)

**Comment by allthesignals** [comment]
Be sure to run `yarn run test:e2e`

**Comment by godfreyyeung** [comment]
# Issue Decomposition

This issue can actually be broken down into two parts: 
  1. We need a legitimate test database, so that we can have a controlled environment to run our backend tests.
  2. Once we have a legitimate test database, we can then write end-to-end (e2e) tests. e2e tests will provide a high return on investment since they provides good coverage of both controllers and SQL queries.

# Implementation Plan 

## Questions

 - [ ] Which of current tests use Nock and which directly connect to the database?
 - [ ] For those that use Nock, do we want to convert them to connect to the database?
 - [ ] Should we load sample rows, or just table schema?
